# Practice for One-to-Many and Many-to-Many Joins for SQL

Import libraries and connect to the database
- Include the relevant imports, then connect to the database located at data.sqlite.

In [4]:
# Run this code without change

import sqlite3
import pandas as pd

conn = sqlite3.connect('data.sqlite')

In [5]:
pd.read_sql( 
"""
SELECT * FROM employees
""", conn).head()

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056,Sale Manager (EMEA)

In [6]:
pd.read_sql(
""" 
SELECT * FROM offices
""",conn).head()

,officeCode,city,phone,addressLine1,addressLine2,state,country,postalCode,territory
0,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
1,2,Boston,+1 215 837 0825,1550 Court Place,Suite 102,MA,USA,02107,NA
2,3,NYC,+1 212 555 3000,523 East 53rd Street,apt. 5A,NY,USA,10022,NA
3,4,Paris,+33 14 723 4404,43 Rue Jouffroy D'abbans,,,France,75017,EMEA
4,5,Tokyo,+81 33 224 5000,4-1 Kioicho,,Chiyoda-Ku,Japan,102-8578,Japan

In [8]:
pd.read_sql(
"""
SELECT * FROM customers
""",conn).head()

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",,Nantes,,44000,France,1370,21000
1,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,,Las Vegas,NV,83030,USA,1166,71800
2,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611,117300
3,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",,Nantes,,44000,France,1370,118200
4,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,Norway,1504,81700

In [9]:
pd.read_sql(""" 
SELECT * FROM products
""", conn).head()

,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,S10_1678,1969 Harley Davidson Ultimate Chopper,Motorcycles,1:10,Min Lin Diecast,"This replica features working kickstand, front...",7933,48.81,95.70
1,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30
2,S10_2016,1996 Moto Guzzi 1100i,Motorcycles,1:10,Highway 66 Mini Classics,"Official Moto Guzzi logos and insignias, saddl...",6625,68.99,118.94
3,S10_4698,2003 Harley-Davidson Eagle Drag Bike,Motorcycles,1:10,Red Start Diecast,"Model features, official Harley Davidson logos...",5582,91.02,193.66
4,S10_4757,1972 Alfa Romeo GTA,Classic Cars,1:10,Motor City Art Classics,Features include: Turnable front wheels; steer...,3252,85.68,136.00

In [10]:
pd.read_sql(""" 
SELECT * FROM orders
""", conn).head()

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber
0,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,,363
1,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128
2,10102,2003-01-10,2003-01-18,2003-01-14,Shipped,,181
3,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121
4,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,,141

1. Employees and Their Offices (a One-to-One Join)
- Select all of the employees including their first name and last name along with the city and state of the office that they work out of (if they have one).
- Include all employees and order them by their first name, then their last name.

In [11]:
# Your code here

q = """
SELECT firstName, lastName, city, state
FROM employees
JOIN offices
    USING(officeCode)
ORDER BY firstName, lastName
;
"""
df = pd.read_sql(q, conn)
print('Total number of results:', len(df))
df.head()

Total number of results: 23

  firstName lastName           city state
0      Andy   Fixter         Sydney
1   Anthony      Bow  San Francisco    CA
2     Barry    Jones         London
3     Diane   Murphy  San Francisco    CA
4  Foon Yue    Tseng            NYC    NY

2. Customers and Their Orders (a One-to-Many Join)
- Select all of the customer contacts (first and last names) along with details for each of the customers' order numbers, order dates, and statuses.

In [12]:
# Your code here

q = """
SELECT
    contactFirstName,
    contactLastName,
    orderNumber,
    orderDate,
    status
FROM customers
JOIN orders
    USING(customerNumber)
;
"""
df = pd.read_sql(q, conn)
print('Total number of results:', len(df))
df.head()

Total number of results: 326

  contactFirstName contactLastName  orderNumber   orderDate   status
0          Carine          Schmitt        10123  2003-05-20  Shipped
1          Carine          Schmitt        10298  2004-09-27  Shipped
2          Carine          Schmitt        10345  2004-11-25  Shipped
3             Jean            King        10124  2003-05-21  Shipped
4             Jean            King        10278  2004-08-06  Shipped

3. Customers and Their Payments (Another One-to-Many Join)
- Select all of the customer contacts (first and last names) along with details for each of the customers' payment amounts and date of payment.
- Sort these results in descending order by the payment amount.

In [13]:
# Your code here

q = """
SELECT
    contactFirstName,
    contactLastName,
    amount,
    paymentDate
FROM customers
JOIN payments
    USING(customerNumber)
ORDER BY amount DESC
;
"""
df = pd.read_sql(q, conn)
print('Total number of results:', len(df))
df.head()

Total number of results: 273

  contactFirstName contactLastName     amount paymentDate
0           Diego           Freyre  120166.58  2005-03-18
1           Diego           Freyre  116208.40  2004-12-31
2            Susan          Nelson  111654.40  2003-08-15
3             Eric       Natividad  105743.00  2003-12-26
4            Susan          Nelson  101244.59  2005-03-05

4. Orders, Order Details, and Product Details (a Many-to-Many Join)
- Select all of the customer contacts (first and last names) along with the product names, quantities, and date ordered for each of the customers and each of their orders.
- Sort these in descending order by the order date.
- Note: This will require joining four tables.

In [ ]:
# Your code here

q = """
SELECT
    contactFirstName,
    contactLastName,
    productName,
    quantityOrdered,
    orderDate
FROM customers
JOIN orders
    USING(customerNumber)
JOIN orderdetails
    USING(orderNumber)
JOIN products
    USING (productCode)
ORDER BY orderDate DESC
;"""
df = pd.read_sql(q, conn)
print('Total number of results:', len(df))
df.head()

Total number of results: 2996

,contactFirstName,contactLastName,productName,quantityOrdered,orderDate
0,Janine,Labrune,1962 LanciaA Delta 16V,38,2005-05-31
1,Janine,Labrune,1957 Chevy Pickup,33,2005-05-31
2,Janine,Labrune,1998 Chrysler Plymouth Prowler,28,2005-05-31
3,Janine,Labrune,1964 Mercedes Tour Bus,38,2005-05-31
4,Janine,Labrune,1926 Ford Fire Engine,19,2005-05-31