# Practice for Join Statements with SQL

Import the necessary packages and connect to the database 'data.sqlite'.

In [1]:
# Run without change

# Libraries and database

import sqlite3
import pandas as pd

conn = sqlite3.connect('data.sqlite')

In [24]:
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
print(tables)

           name
0  productlines
1       offices
2     customers
3     employees
4  orderdetails
5        orders
6      payments
7      products

In [7]:
pd.read_sql( """ 
SELECT * FROM offices
""", conn )

,officeCode,city,phone,addressLine1,addressLine2,state,country,postalCode,territory
0,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
1,2,Boston,+1 215 837 0825,1550 Court Place,Suite 102,MA,USA,02107,NA
2,3,NYC,+1 212 555 3000,523 East 53rd Street,apt. 5A,NY,USA,10022,NA
3,4,Paris,+33 14 723 4404,43 Rue Jouffroy D'abbans,,,France,75017,EMEA
4,5,Tokyo,+81 33 224 5000,4-1 Kioicho,,Chiyoda-Ku,Japan,102-8578,Japan
5,6,Sydney,+61 2 9264 2451,5-11 Wentworth Avenue,Floor #2,,Australia,NSW 2010,APAC
6,7,London,+44 20 7877 2041,25 Old Broad Street,Level 7,,UK,EC2N 1HN,EMEA
7,27,Boston,+1 977 299 8345,105 Cambridge Street,,MA,USA,02331,NA

In [5]:
pd.read_sql( """ 
SELECT * FROM employees
""" ,conn)

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102,Sales Rep

In [20]:
pd.read_sql( """ 
SELECT * FROM customers
""" ,conn)

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",,Nantes,,44000,France,1370,21000
1,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,,Las Vegas,NV,83030,USA,1166,71800
2,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611,117300
3,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",,Nantes,,44000,France,1370,118200
4,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,Norway,1504,81700
...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,,Philadelphia,PA,71270,USA,1323,72600
118,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,,Brisbane,CA,94217,USA,1165,60300
119,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,,London,,WA1 1DP,UK,1501,43300
120,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,,Boston,MA,51003,USA,1188,85100
121,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',,Auckland,,,New Zealand,1612,110000

In [25]:
pd.read_sql( """ 
SELECT * FROM products
""", conn)

,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,S10_1678,1969 Harley Davidson Ultimate Chopper,Motorcycles,1:10,Min Lin Diecast,"This replica features working kickstand, front...",7933,48.81,95.70
1,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30
2,S10_2016,1996 Moto Guzzi 1100i,Motorcycles,1:10,Highway 66 Mini Classics,"Official Moto Guzzi logos and insignias, saddl...",6625,68.99,118.94
3,S10_4698,2003 Harley-Davidson Eagle Drag Bike,Motorcycles,1:10,Red Start Diecast,"Model features, official Harley Davidson logos...",5582,91.02,193.66
4,S10_4757,1972 Alfa Romeo GTA,Classic Cars,1:10,Motor City Art Classics,Features include: Turnable front wheels; steer...,3252,85.68,136.00
...,...,...,...,...,...,...,...,...,...
105,S700_3505,The Titanic,Ships,1:700,Carousel DieCast Legends,"Completed model measures 19 1/2 inches long, 9...",1956,51.09,100.17
106,S700_3962,The Queen Mary,Ships,1:700,Welly Diecast Productions,Exact replica. Wood and Metal. Many extras inc...,5088,53.63,99.31
107,S700_4002,American Airlines: MD-11S,Planes,1:700,Second Gear Diecast,Polished finish. Exact replia with official lo...,8820,36.27,74.03
108,S72_1253,Boeing X-32A JSF,Planes,1:72,Motor City Art Classics,"10"" Wingspan with retractable landing gears.Co...",4857,32.77,49.66
109,S72_3212,Pont Yacht,Ships,1:72,Unimax Art Galleries,Measures 38 inches Long x 33 3/4 inches High. ...,414,33.30,54.60

1. Select the names (frist and last) of all employees in Boston

In [12]:
# Your code here

pd.read_sql( """ 
SELECT firstName, lastName 
FROM employees 
JOIN offices ON employees.officeCode = offices.officeCode
WHERE city = 'Boston'
""" ,conn)

  firstName   lastName
0     Julie   Firrelli
1     Steve  Patterson

2. Are there any offices that have zero employees?

In [19]:

# q = """
# SELECT *
#  FROM orderdetails AS od
#    JOIN products AS p
#      ON od.productCode = p.productCode
#  LIMIT 10;
# """
# pd.read_sql(q, conn)


pd.read_sql( """ 
SELECT 
    o.officeCode,
    o.city,
    COUNT(e.employeeNumber) AS n_employees
    FROM offices AS o
    LEFT JOIN employees AS e 
           ON o.officeCode = e.officeCode
GROUP BY o.officeCode
HAVING n_employees = 0;
""" ,conn )

   officeCode    city  n_employees
0          27  Boston            0

In [15]:
# Your code here

pd.read_sql( """ 
SELECT 
    o.officeCode,
    o.city,
    COUNT(e.employeeNumber) AS n_employees
FROM offices AS o
LEFT JOIN employees AS e USING(officeCode)
GROUP BY officeCode
HAVING n_employees = 0;
""" ,conn )

   officeCode    city  n_employees
0          27  Boston            0

3. How many customers are there per office?

In [23]:
# Your code here

pd.read_sql( """ 
SELECT 
    o.officeCode,
    o.city,
    COUNT(c.customerNumber) AS n_customers
FROM offices AS o
JOIN employees AS e
    USING(officeCode)
JOIN customers AS c
    ON e.employeeNumber = c.salesRepEmployeeNumber
GROUP BY officeCode
;
""" , conn)

   officeCode           city  n_customers
0           1  San Francisco           12
1           2         Boston           12
2           3            NYC           15
3           4          Paris           29
4           5          Tokyo            5
5           6         Sydney           10
6           7         London           17

4. Display the names of every individual product that each employee has sold as a dataframe.

In [26]:
# Your code here

# employees
# products

pd.read_sql( """ 


SELECT firstName, lastName, productName
FROM employees AS e
JOIN customers AS c
    ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders
    USING(customerNumber)
JOIN orderdetails
    USING(orderNumber)
JOIN products
    USING(productCode)
;
""" , conn)

     firstName  lastName                                  productName
0       Leslie  Jennings                               1958 Setra Bus
1       Leslie  Jennings                       1940 Ford Pickup Truck
2       Leslie  Jennings                      1939 Cadillac Limousine
3       Leslie  Jennings  1996 Peterbilt 379 Stake Bed with Outrigger
4       Leslie  Jennings                            1968 Ford Mustang
...        ...       ...                                          ...
2991    Martin    Gerard                  1954 Greyhound Scenicruiser
2992    Martin    Gerard       1950's Chicago Surface Lines Streetcar
2993    Martin    Gerard             Diamond T620 Semi-Skirted Tanker
2994    Martin    Gerard                           1911 Ford Town Car
2995    Martin    Gerard             1936 Mercedes Benz 500k Roadster

[2996 rows x 3 columns]

5. Display the number of products each employee has sold
- Alphabetize the results by employee last name.
- Use the quantityOrdered column from orderDetails.
- Think about how to group the data when some employees might have the same first or last name.

In [28]:
# Your code here

q = """
SELECT firstName, lastName, SUM(quantityOrdered) as total_products_sold
FROM employees AS e
JOIN customers AS c
    ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders
    USING(customerNumber)
JOIN orderdetails
    USING(orderNumber)
GROUP BY firstName, lastName
ORDER BY lastName
;
"""
pd.read_sql(q, conn)

   firstName   lastName  total_products_sold
0       Loui     Bondur                 6186
1      Larry       Bott                 8205
2     Pamela   Castillo                 9290
3      Julie   Firrelli                 4227
4       Andy     Fixter                 6246
5     Martin     Gerard                 4180
6     Gerard  Hernandez                14231
7     Leslie   Jennings                11854
8      Barry      Jones                 7486
9      Peter      Marsh                 6632
10      Mami      Nishi                 4923
11     Steve  Patterson                 5561
12    Leslie   Thompson                 4056
13  Foon Yue      Tseng                 5016
14    George     Vanauf                 7423

6.  Display the names of employees who have sold more than 200 different products.

In [29]:
# Your codde here

# Recall that HAVING is used for filtering after an aggregation
q = """
SELECT firstName, lastName, COUNT(productCode) as different_products_sold
FROM employees AS e
JOIN customers AS c
    ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders
    USING(customerNumber)
JOIN orderdetails
    USING(orderNumber)
GROUP BY firstName, lastName
HAVING different_products_sold > 200
ORDER BY lastName
;
"""
pd.read_sql(q, conn)

  firstName   lastName  different_products_sold
0     Larry       Bott                      236
1    Pamela   Castillo                      272
2    Gerard  Hernandez                      396
3    Leslie   Jennings                      331
4     Barry      Jones                      220
5    George     Vanauf                      211

In [30]:
conn.close()